version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: ewallet-database
    env_file:
      - .env
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}"
    volumes:
      - data-postgres:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: ewallet-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "${RABBITMQ_CLIENT_PORT}:${RABBITMQ_CLIENT_PORT}"
    volumes:
      - ~/.docker-conf/rabbitmq/data:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log:/var/log/rabbitmq
    network_mode: "bridge"

volumes:
  data-postgres:
    driver: local
